ALTER TABLE books
  ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE';

UPDATE books
  SET status = 'AVAILABLE'
  WHERE status IS NULL;

ALTER TABLE books
  ADD CONSTRAINT chk_books_status
  CHECK (status IN ('AVAILABLE','RESERVED','BORROWED','LOST', 'DELAYED'));
