CREATE TABLE IF NOT EXISTS publishers (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME,
    updated_at DATETIME,
    deleted BOOLEAN DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;